name: car-following-sumo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
      - eclipse-sumo
      - traci
      - sumolib
